In [2]:
import pandas as pd
import numpy as np

In [9]:
df_acc = pd.read_csv('moneycraft_accounts.csv')
df_acc['month'] = pd.PeriodIndex(df_acc['month'], freq='M')
df_acc.head()

,customer_id,month,acquisition_channel,region,age_band,account_tier,monthly_fee,joined_on_promo
0,1,2022-01,Comparison Site,Scotland,25-34,Classic,0,False
1,2,2022-01,Online,London,55-64,Silver,11,False
2,3,2022-01,Branch,South East,25-34,Platinum,28,False
3,4,2022-01,Referral,London,25-34,Silver,0,True
4,5,2022-01,Comparison Site,South East,35-44,Silver,11,False

In [10]:
df_mark = pd.read_csv('moneycraft_marketing_spend.csv')
df_mark['month'] = pd.PeriodIndex(df_mark['month'], freq='M')
df_mark.head()

     month          channel  spend_gbp
0  2022-01           Branch     7310.0
1  2022-01       Broker/IFA     4014.0
2  2022-01  Comparison Site     3162.0
3  2022-01           Online     3945.0
4  2022-01         Outbound     4899.0

In [12]:
df_clos = pd.read_csv('moneycraft_closure_reasons.csv')
df_clos['close_month'] = pd.PeriodIndex(df_clos['close_month'], freq='M')
df_clos.head()

   customer_id close_month         reason_code
0        10755     2024-05   Switched provider
1         7582     2025-01  Unhappy with perks
2         2162     2024-11       Fees too high
3         3016     2023-02   Switched provider
4          564     2022-07        Poor service

In [15]:
df_mark.groupby('channel')['spend_gbp'].sum().sort_values(ascending=False)

channel
Branch             377567.0
Online             269322.0
Outbound           239264.0
Broker/IFA         195020.0
Comparison Site    182406.0
Referral           112021.0
Name: spend_gbp, dtype: float64

In [19]:
first = df_acc.sort_values('month').drop_duplicates('customer_id')
joiners = first.groupby(['month', 'acquisition_channel']).size()

spend = df_mark.set_index(['month', 'channel'])['spend_gbp']

cac = (spend / joiners).round(2).unstack()
cac

channel  Branch  Broker/IFA  Comparison Site  Online  Outbound  Referral
month
2022-01  149.18      191.14            39.04   68.02    125.62     58.50
2022-02  154.55      198.90            40.83   62.22    120.61     58.60
2022-03  154.36      214.96            38.94   66.59    114.83     56.87
2022-04  155.12      181.38            35.91   68.04    119.32     62.53
2022-05  148.83      201.61            39.69   73.50    125.49     55.09
2022-06  158.06      187.95            38.71   72.84    113.42     60.33
2022-07  141.37      198.74            40.14   70.03    113.10     62.86
2022-08  138.02      199.85            36.94   63.47    111.29     58.66
2022-09  149.87      206.56            40.50   69.21    121.87     62.79
2022-10  146.91      199.58            38.66   67.01    119.33     61.04
2022-11  166.13      206.77            39.81   79.74    121.05     59.50
2022-12  136.57      212.78            39.92   69.76    118.75     63.38
2023-01  144.04      187.35            39.50   70.16    113.02     60.91
2023-02  144.44      196.43            37.99   71.69    120.38     61.25
2023-03  157.70      208.72            38.18   70.46    124.94     58.29
2023-04  161.44      189.18            36.70   66.96    127.28     57.07
2023-05  144.97      201.68            40.02   69.68    117.24     57.72
2023-06  152.97      202.78            38.34   69.52    120.45     59.23
2023-07  156.41      198.70            38.67   66.89    128.83     61.93
2023-08  156.47      187.95            39.34   69.07    128.15     60.25
2023-09  167.10      189.63            41.38   70.82    132.42     57.15
2023-10  144.22      188.19            38.72   71.68    121.10     64.00
2023-11  155.18      198.09            40.37   73.00    129.60     59.22
2023-12  145.85      206.00            37.13   66.84    111.24     57.66
2024-01  159.85      194.15            40.91   70.11    130.30     55.94
2024-02  158.06      176.44            41.51   72.75    132.65     61.59
2024-03  161.86      202.47            39.92   71.81    111.83     58.90
2024-04  151.58      213.46            39.71   69.65    113.75     55.43
2024-05  160.96      191.03            42.59   69.75    127.07     63.97
2024-06  153.01      195.62            41.13   66.13    127.20     57.13
2024-07  154.19      194.75            39.46   67.47    125.74     63.68
2024-08  157.33      209.86            43.32   71.28    118.40     58.66
2024-09  139.43      216.32            42.31   71.39    117.58     61.32
2024-10  156.00      207.53            41.88   71.73    122.77     54.82
2024-11  147.09      199.37            39.31   74.88    121.65     58.73
2024-12  153.36      197.85            39.55   68.74    128.36     62.77