In [2]:
import pandas as pd
import numpy as np

In [9]:
df_acc = pd.read_csv('moneycraft_accounts.csv')
df_acc['month'] = pd.PeriodIndex(df_acc['month'], freq='M')
df_acc.head()

,customer_id,month,acquisition_channel,region,age_band,account_tier,monthly_fee,joined_on_promo
0,1,2022-01,Comparison Site,Scotland,25-34,Classic,0,False
1,2,2022-01,Online,London,55-64,Silver,11,False
2,3,2022-01,Branch,South East,25-34,Platinum,28,False
3,4,2022-01,Referral,London,25-34,Silver,0,True
4,5,2022-01,Comparison Site,South East,35-44,Silver,11,False

In [10]:
df_mark = pd.read_csv('moneycraft_marketing_spend.csv')
df_mark['month'] = pd.PeriodIndex(df_mark['month'], freq='M')
df_mark.head()

     month          channel  spend_gbp
0  2022-01           Branch     7310.0
1  2022-01       Broker/IFA     4014.0
2  2022-01  Comparison Site     3162.0
3  2022-01           Online     3945.0
4  2022-01         Outbound     4899.0

In [11]:
df_clos = pd.read_csv('moneycraft_closure_reasons.csv')
df_clos['close_month'] = pd.PeriodIndex(df_clos['close_month'], freq='M')
df_clos.head()

   customer_id close_month         reason_code
0        10755     2024-05   Switched provider
1         7582     2025-01  Unhappy with perks
2         2162     2024-11       Fees too high
3         3016     2023-02   Switched provider
4          564     2022-07        Poor service

In [7]:
switches = (df_acc.sort_values(['customer_id', 'month'])
                  .groupby('customer_id')['account_tier']
                  .apply(lambda s: (s != s.shift()).sum() - 1))

switches.head(20)

customer_id
1     0
2     2
3     2
4     0
5     1
6     2
7     0
8     1
9     2
10    1
11    0
12    0
13    0
14    3
15    0
16    0
17    0
18    1
19    2
20    3
Name: account_tier, dtype: int64